---

name: Release to Ansible Galaxy.

on:
  workflow_call:
    inputs:
      github_release_tag:
        required: true
        type: string
    secrets:
      github_token:
        required: true
      galaxy_api_key:
        required: true

jobs:
  release-to-galaxy:
    runs-on: ubuntu-latest
    steps:
      # release tag on Github.
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new release.
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.github_token }}
          automatic_release_tag: ${{ inputs.github_release_tag }}
          prerelease: false
          title: "Release ${{ inputs.github_release_tag }}"

      # push to Ansible Galaxy.
      - name: Set up Python 3
        uses: actions/setup-python@v5
      # 
      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Import role to Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.galaxy_api_key }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
